server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:13306/identity_service"
    username: root
    password: secret
# only develop
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true